# Site settings
title: symdiff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://symdiff.github.io" # the base hostname & protocol for your site
github_username:  symdiff

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: coderay